return {
    start_with_mod = false,
    trigger_type = 1,
    activation_threashold = 1,
    activation_mode = 1,
    starting_mods = {},
    activation_blacklist = {
        ["Lovely"] = true,
        ["SuperRogue"] = true,
        ["JokerDisplay"] = true,
        ["TheFamily"] = true,
        ["Talisman"] = true,
        ["Handy"] = true,
        ["bettertags"] = true,
        ["toomanyjokers"] = true,
        ["foxy"] = true,
        ["blueprint"] = true,
        ["Friends of James"] = true,
        ["galdur"] = true,
        ["CardSleeves"] = true,
        ["DebugPlus"] = true,
        ["VanillaRemade"] = true,
        ["SlayTheJokers"] = true
    },
}