[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

#Patch SMODS ante_end to use upcoming functionality for compat
[[patches]]
[patches.pattern]
target = 'functions/state_events.lua'
pattern = '''
delay(0.4); ease_ante(1, true); delay(0.4); check_for_unlock({type = 'ante_up', ante = G.GAME.round_resets.ante + 1})
'''
position = 'at'
payload = '''
delay(0.4); SMODS.ante_end = true; ease_ante(1); SMODS.ante_end = nil; delay(0.4); check_for_unlock({type = 'ante_up', ante = G.GAME.round_resets.ante + 1})
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = '''
function ease_ante(mod, ante_end)
    local flags = SMODS.calculate_context({modify_ante = mod, ante_end = ante_end})
'''
position = 'at'
payload = '''
function ease_ante(mod)
	local flags = SMODS.calculate_context({modify_ante = mod, ante_end = SMODS.ante_end})
'''
match_indent = true
times = 1

[[patches]]
[patches.pattern]
target = '''=[SMODS _ "src/overrides.lua"]'''
pattern = '''
SMODS.calculate_context({ante_change = mod, ante_end = ante_end})
'''
position = 'at'
payload = '''
SMODS.calculate_context({ante_change = mod, ante_end = SMODS.ante_end})
'''
match_indent = true
times = 1

# Ortalab Compat
[[patches]] # Small and Big Blind pool manipulation
[patches.pattern]
target = '''=[SMODS ortalab "util/functions.lua"]'''
pattern = '''
for k, v in pairs(G.GAME.banned_keys) do
    if eligible_bosses[k] then eligible_bosses[k] = nil end
end
'''
position = 'after'
payload = '''
for k, v in pairs(eligible_bosses) do
    if G.P_BLINDS[k] and not SuperRogue.is_object_mod_active(G.P_BLINDS[k], {type = 'Boss'}) then eligible_bosses[k] = nil end
end
if not next(eligible_bosses) then
    eligible_bosses['bl_manacle'] = true
end
'''
match_indent = true
times = 2

[[patches]] # Mythos shop slot compat
[patches.pattern]
target = 'game.lua'
pattern = '''
elseif G.GAME.ortalab.vouchers.mythos_shop_slot then
'''
position = 'at'
payload = '''
elseif G.GAME.ortalab.vouchers.mythos_shop_slot and G.GAME.sr_active_mod_pool['ortalab'] then
'''
match_indent = true
times = 1

# Cryptid Compat
[[patches]] # Accomodate pool rates totalling for Cryptid patches
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
total_rate = total_rate + ( G.GAME[v:lower()..'_rate'] * (G.GAME.cry_percrate[v:lower()]/100) )
'''
position = 'at'
payload = '''
if SuperRogue.is_pool_available(v) then
    total_rate = total_rate + ( G.GAME[v:lower()..'_rate'] * (G.GAME.cry_percrate[v:lower()]/100) )
end
'''
match_indent = true
times = 1

[[patches]] # Accomodate pool rates table inserting for Cryptid patches
[patches.pattern]
target = 'functions/UI_definitions.lua'
pattern = '''
table.insert(rates, { type = v, val = G.GAME[v:lower()..'_rate'] * ((num or 100) / 100) })
'''
position = 'at'
payload = '''
if SuperRogue.is_pool_available(v) then
    table.insert(rates, { type = v, val = G.GAME[v:lower()..'_rate'] * ((num or 100) / 100) })
end
'''
match_indent = true
times = 1
